kroxylicious/kroxylicious.github.io

Gemfile.lock, _config.yml, _includes/redhat-footer.html, _sass/kroxylicious.scss, index.markdown
Add the registration mark to first usage of Apache Kafka in the hero and to the footer.
=> Apachetrademark adjustments

_layouts/default.html, _layouts/index.html, _layouts/overview.html, _sass/kroxylicious.scss, index.markdown, overview.markdown
1) Added hero band with new text as per original PR 
2) Added "row" to layout to remove unwanted global side padding so the page renders at true full width. 
3) change from Josefin to Questrail font.
=> Re-work Hero band and change global font

Gemfile.lock, _layouts/index.html
New tag line!
I added Topic encryption to the suggested subtitle as that is the one thing we have today and we are rightly proud of it.
=> Update tag line

_includes/footer.html, _use_cases/encryption-at-rest.markdown, assets/2023-12-19-release-0_4_0-ee-overview.excalidraw, assets/encryption-at-rest_solution.excalidraw
rh-pre-commit.version: 2.0.1
rh-pre-commit.check-secrets: ENABLED
=> Update references to `EnvelopeEncryption` to be `RecordEncryption`.

_layouts/index.html
=> Hero buttons

_posts/2024-06-07-release-0_6_0.md
=> Fix typo/grammar

_posts/2024-08-29-release-0_8_0.md
=> Add 0.8.0 release blog

_data/kroxylicious.yml, docs/v0.8.0/_files/_assets/attributes.adoc, docs/v0.8.0/_files/_assets/trademarks.adoc, docs/v0.8.0/_files/assemblies/assembly-aws-kms.adoc, docs/v0.8.0/_files/assemblies/assembly-built-in-filters.adoc, docs/v0.8.0/_files/assemblies/assembly-hashicorp-vault.adoc, docs/v0.8.0/_files/assemblies/assembly-multi-tenancy-filter.adoc, docs/v0.8.0/_files/assemblies/assembly-overview.adoc, docs/v0.8.0/_files/assemblies/assembly-record-encryption-filter.adoc, docs/v0.8.0/_files/assemblies/assembly-record-validation-filter.adoc, docs/v0.8.0/_files/index.adoc, docs/v0.8.0/_files/modules/con-community-filters.adoc, docs/v0.8.0/_files/modules/con-custom-filters.adoc, docs/v0.8.0/_files/modules/con-deploying.adoc, docs/v0.8.0/_files/modules/con-operating.adoc, docs/v0.8.0/_files/modules/con-proxy-overview.adoc, docs/v0.8.0/_files/modules/multi-tenancy/proc-multi-tenancy.adoc, docs/v0.8.0/_files/modules/oauthbearer/con-oauthbearer.adoc, docs/v0.8.0/_files/modules/record-encryption/aws-kms/con-aws-kms-key-creation.adoc, docs/v0.8.0/_files/modules/record-encryption/aws-kms/con-aws-kms-service-config.adoc, docs/v0.8.0/_files/modules/record-encryption/aws-kms/con-aws-kms-setup.adoc, docs/v0.8.0/_files/modules/record-encryption/con-record-encryption-overview.adoc, docs/v0.8.0/_files/modules/record-encryption/hashicorp-vault/con-vault-key-creation.adoc, docs/v0.8.0/_files/modules/record-encryption/hashicorp-vault/con-vault-service-config.adoc, docs/v0.8.0/_files/modules/record-encryption/hashicorp-vault/con-vault-setup.adoc, docs/v0.8.0/_files/modules/record-encryption/proc-configuring-record-encryption-filter.adoc, docs/v0.8.0/_files/modules/record-validation/proc-record-validation.adoc, docs/v0.8.0/index.adoc
Add v0.8.0 docs
Copied from kroxylicious/kroxylicious@dd852e28546f27d0aee89dca5a86ee5295762a87
=> Add v0.8.0 docs

_posts/2024-08-29-release-0_8_0.md
Add note about the version change
=> Add note about the release version

_posts/2024-09-13-junit-ext-and-kafka4.md, _posts/2024-11-07-release-0_9_1-junit-extension.md
Adds an announcement post for Kroxylicious JUnit Extension v0.9.1, and fixes some issues with spelling, etc. in the last blog post (which was also about the Junit Extension).
=> Kroxylicious JUnit Extension 0.9.1 Release Blog Post

atproto-did.markdown
Atproto aka BlueSky means we can get @kroxylicious.io as our handle 😁
=> Verify domain ownership

.well-known/atproto-did, _config.yml, atproto-did.markdown
rh-pre-commit.version: 2.0.1
rh-pre-commit.check-secrets: ENABLED
=> try and serve things as plain text.

_posts/2024-12-17-release-0_9_0.md
Signed-off-by: Sam Barker <sbarker@redhat.com>
rh-pre-commit.version: 2.0.1
rh-pre-commit.check-secrets: ENABLED
=> Add an extra category to build a non-conflicting URL

.github/workflows/jekyll-gh-pages.yml
Signed-off-by: Sam Barker <sbarker@redhat.com>
rh-pre-commit.version: 2.0.1
rh-pre-commit.check-secrets: ENABLED
=> upgrade to deploy-pages v4

docs/v0.10.0/_files/modules/configuring/con-configuring-vc-client-tls.adoc, docs/v0.10.0/_files/modules/configuring/con-configuring-vc-target-tls.adoc
reflecting the post release docs changes from https://github.com/kroxylicious/kroxylicious/pull/1801
=> allow -> allowed & deny -> denied in yaml snippets

_includes/footer.html, _includes/nav.html, _includes/nested-card-tabbed/tab.html, _includes/redhat-footer.html, _layouts/blog.html, _layouts/docs.html, _layouts/index.html, _layouts/overview.html, _layouts/quickstart.html, _layouts/use-cases.html, _quickstarts/deploy.markdown, _quickstarts/develop.markdown, _sass/kroxylicious.scss, _use_cases/encryption-at-rest.markdown, _use_cases/schema_validation_and_enforecement.markdown, index.markdown, overview.markdown
Using the [HTML Codesniffer bookmarklet](https://github.com/squizlabs/HTML_CodeSniffer), I'm going through the website and trying to fix the accessibility issues mentioned in #99. Some of these will likely be in the docs which might be a more complicated fix (we'll have to update all the versions of the docs in the website repo, and then also make the same changes in the main Kroxylicious repo).
Closes #99
=> Accessibility Fixes

docs/v0.11.0/_files/_assets/attributes.adoc, docs/v0.12.0/_files/_assets/attributes.adoc
…rgets etc for the release.
Fixes: https://github.com/kroxylicious/kroxylicious.github.io/issues/132
=> Update kroxylicious release versions so we link to correct javadoc targets etc for the release

Gemfile.lock, _includes/redhat-footer.html, _sass/kroxylicious.scss
Screen shot of rendered changes:
=> Include a reference to being part of Commonhaus in our footer as requested by the foundation.

Gemfile.lock, _posts/2025-06-23-release-0_13_0.md
I will need to update the change log link and validate the download link once the release itself is complete.
=> Announce the release of Kroxylicious 0.13.0

.github/workflows/pr-build.yml
Hasty auto-merge burned fingers :bow:
=> Use fixed-string grep as we are searching for a literal

documentation/0.14.0/html/proxy-quick-start/content.html
There is now styling to add a top border to the sect1 divs so the hrs are redundant and look off.
=> Remove horizontal rules from proxy quickstart

run-snapshot.sh
The main repo has been refactored so that documentation is generated in the kroxylicious-docs module.
=> run-snapshot.sh uses new kroxylicious module
