- static/index.html
Slack is invite only. This link never expires but only works for 400 invites.
> Add slack invite link

- _includes/footer.html
- _layouts/default.html
On large screens the footer does not stick to the bottom of the browser window.
This PR fixes that issue, while retaining the positioning on smaller screens and mobile devices.
> make footer stick to the bottom of the page on all screen sizes

- .github/workflows/jekyll-gh-pages.yml
- Gemfile.lock
- README.md
- _includes/nav.html
- bootstrap_setup.sh
- local_setup.sh
Update workflow to use jekyll instead of github-pages gem, fix docs link for places not using the kroxylicious domain.
We are currently using a GitHub Action that is pulling in the github-pages gem instead of the Jekyll one, so this PR fixes that by using the Jekyll-recommended workflow (rather than the GitHub-recommended one) which installs and sets everything up manually.
There was also a problem with using absolute_url for the docs link when rendering the site on any domain that wasn't kroxylicious.io, where it would append the path incorrectly (this was only a problem for `/docs` because it's not rendered by Jekyll). Using the relative_url filter for this link should fix this for people who want to test their changes under their own GitHub account, while still retaining functionality …
> Fixes for GitHub Actions workflow and development work

- _sass/kroxylicious.scss
The primary, secondary, light, and dark colour palette overrides in _scss/kroxylicious.scss were not applying correctly due to an issue with import ordering. This fixes that (and some other nonsense variables we had floating around), so we're actually using the Kroxylicious brand colours across the site.
> Fix bootstrap colour palette and import order

- overview.markdown
The "documentation" link is directing to an 404 page: https://kroxylicious.io/overview/kroxylicious . Fix it. 
Question: Do we have a label with the latest version number? Otherwise, we need to remember to update it when the new version released.
> fix borken doc link

- bootstrap_setup.sh
Does what it says on the tin, bumps Bootstrap to the latest [version (v5.3.3)](https://github.com/twbs/bootstrap/releases/tag/v5.3.3).
> bump bootstrap to v5.3.3

- Gemfile.lock
- docs/v0.5.1/index.adoc
- docs/v0.6.0/index.adoc
- docs/v0.7.0/index.adoc
The docs pages for versions up to and including v0.5.0 have a message at the top which reads `This documentation is for an older release of Kroxylicious, and may not reflect current functionality.` This message is missing from the docs for v0.5.1, v0.6.0, and v0.7.0 (v0.8.0 is the current release so shouldn't have this message), so this PR is just to add that missing message to those pages.
> Add missing "old docs" warning messages to previous release docs pages

- docs/v0.9.0/index.adoc
This extra newline is breaking the documentation rendering on the website for [0.9.0](https://kroxylicious.io/docs/v0.9.0/)
😱😱😱😱😱😱😱😱😱😱😱😱😱😱
> Fix doc generation for v0.9.0

- .github/workflows/jekyll-gh-pages.yml
Upgrade actions/upload-pages-artifact from v2 to v3 to fix broken workflow [due to deprecation of actions/upload-artifact v3](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).
actions/upload-pages-artifact v3 uses  actions/upload-artifact v4.
> Upgrade to actions/upload-pages-artifact@v3 in GitHub Actions

- docs/v0.10.0/_files/_assets/attributes.adoc
Fix `KroxyliciousVersion` in AsciiDoc properties for v0.10.0 docs.
> Fix version number in 0.10.0 docs

- _data/kroxylicious.yml
- _includes/nav.html
- _layouts/default.html
- _sass/kroxylicious.scss
- docs/v0.10.0/index.adoc
- docs/v0.8.0/index.adoc
- docs/v0.9.0/index.adoc
Fixes #106
Work in progress to add new docs subsections dynamically to dropdown nav (done), ~~and move old docs versions to an "older versions" index page and out of the main nav menu (in progress)~~ <- moving this to a second PR.
Trying to simplify things and avoid clutter.
Also includes some updating of "this is an older version" warnings on old docs versions I hadn't got around to adding it to. Probably we should find a better (i.e. not manual) way to do that in future but it's of very low importance.
> DRAFT: Restructure docs navigation

- _includes/asciidoctor-scripts/icons.html
- _includes/asciidoctor-scripts/sectanchors.html
- _layouts/docs.html
- _sass/kroxylicious.scss
- Adds a script in `_includes/asciidoctor-scripts/icons.html` to change some HTML classes on the release docs pages
- Adds some CSS to `_sass/kroxylicious.scss` to fix some missing styles on the release docs pages
- Moves the script to fix sectanchors out of the docs layout file and into `_includes/asciidoctor-scripts/sectanchors.html` to keep things neat
The release docs are currently not formatted correctly on the website. Compare the development docs:
With the latest release docs:
This is because the default Asciidoctor stylesheet is missing from the docs pages, as it's trying to use the ones Jekyll provides for the rest of the site. However the styles used by the rest of the site were not written with the Asciidoctor stylesheet in mind, so they do not apply completely and some things …
> Fix formatting of docs

- _data/kroxylicious.yml
- docs/v0.12.0/_files/index.adoc
Fixes some broken links.  I expect this manual chore will disappear once we start publishing the other docs.
> v0.12.0 docs: Remove links to operator and developer's guide for now

- docs/v0.13.0/_files/assemblies/assembly-operator-api.adoc
- docs/v0.13.0/_files/modules/monitoring/con-prometheus-metrics-proxy.adoc
I'm not sure of the correct permanent fix, but I can see that the prefixing we do of image locations in the source asciidoc is messing up the publication on the website.
This is a temporary workaround.  We need to fix it properly.
> Manually fix image locations with v0.13.0 docs

- .github/workflows/jekyll-gh-pages.yml
- .gitignore
- Dockerfile
This brings the local development and github actions builds closer together. Using the same Dockerfile in both places to build the static content.
1. we build the image and cache the layers it to gha, this means the build step should usually be very fast.
2. we do not copy in all the sources into the image because we mount the sources in locally and in the workflow. this makes the image very cacheable.
3. moves a2s into /usr/local/bin so that the github user id can access it (previously it was under /root).
> Build the website using the same Dockerfile in the github action

- _layouts/guide.html
This wouldn't be visible until we have guides for past versions
(test by updating _data/kroxylicious.yml latestRelease)
> Fix guide layout to show version warning correctly

- _layouts/released-documentation.html
We should know the key to look up from the version.
This removes a spat of warnings from Jekll too:
```
Liquid Warning: Liquid syntax error (line 35): Expected end_of_string but found pipe in "docSet in site.data.documentation | sort: "rank"" in /site/_layouts/released-documentation.html
Liquid Warning: Liquid syntax error (line 45): Unexpected character { in "{{"/documentation/" | append: {{version}} | append: "/" }}" in /site/_layouts/released-documentation.html
... etc
```
> Replace loop over all documentation with lookup

- _config.yml
- _data/documentation/0_10_0.yaml
- _data/documentation/0_11_0.yaml
- _data/documentation/0_12_0.yaml
- _data/documentation/0_13_0.yaml
- _data/documentation/0_14_0-SNAPSHOT.yaml
- _data/documentation/0_1_0.yaml
- _data/documentation/0_2_0.yaml
- _data/documentation/0_3_0.yaml
- _data/documentation/0_4_0.yaml
- _data/documentation/0_4_1.yaml
- _data/documentation/0_5_0.yaml
- _data/documentation/0_5_1.yaml
- _data/documentation/0_6_0.yaml
- _data/documentation/0_7_0.yaml
- _data/documentation/0_8_0.yaml
- _data/documentation/0_9_0.yaml
- _includes/footer.html
- _includes/nav.html
- _layouts/quickstart.html
- _sass/kroxylicious.scss
- docs/quickstart/deploy/index.markdown
- docs/quickstart/develop/index.markdown
- quickstarts.markdown
* Move them from `/quickstarts` to `/doc/quickstart/*/index.markdown`
* Drop the idea of having a tab-per-quickstart. Instead give them each their own page.
* Tweak the scss so the code blocks aren't so huge
* Use markdown syntax for headings
* Drop the `<br/>`
> Rework the quickstarts

- README.md
Update development guide
- update ruby version
- remove reference to `gh-pages` branch as we don't deploy that way anymore
- added container deployment instructions
> Update development guide

- overview.markdown
It links to an old version of the docs and is hardcoded to kroxylicious.io
> Update overview documentation link

- .github/workflows/jekyll-gh-pages.yml
When testing on a fork I want to be able to push to a non-main branch and deploy that, rather than force-pushing to main, which is a bad habit to get into.
> Enable users to manually trigger a deployment from target branch

- .github/workflows/jekyll-gh-pages.yml
- .gitignore
- README.md
The github build action will dump a `JEKYLL_CONFIG_OVERRIDES` action variable into a file `_config-overrides.yml` which will override whatever you want in `_config.yml`.
Why:
It's convenient to be able to deploy the website on a forked repository. Currently this doesn't work smoothly because by default with actions because it builds with kroxylicious.io as the url. The mechanism that configures the baseurl is also not wired up correctly.
To override the url we need to add in an override configuration, so I figure we should use the same mechanism to override baseurl. The fork can set a variable containing both these values.
> Enable github forks to override jekyll config

- _layouts/download-release.html
- _layouts/released-documentation.html
- release-archives/index.md
Deploying on a fork is useful to exercise the github actions if we are working on the build aspects of this repo and it makes it easier to share WIP when hacking on the website. Our forks typically will look like `https://<user>.github.io/kroxylicious.github.io` where the main website is deployed to `https://kroxylicious.io` without any baseurl.
To run on a fork with a base url like https://kroxylicious.io/kroxylicious/ we need the links to all be aware of the baseurl, we have a mixture currently, some work and some don't.
This fixes up:
1. links from the release-archives to the docs/downloads
2. links from the released-documentation pages to the release-archives
3. relative/domain-relative links on the released-documentation pages
4. links from the download-release pages to the …
> Fix documentation/download/release-archive internal links to work with non-empty baseurl

- .github/workflows/pr-build.yml
- Dockerfile
This adds a separate workflow for PR CI, just checking we can build the site in production mode. We might need an accompanying change in the settings to require the checks to succeed before users can merge PRs.
The workflow is similar to the automation that deploys the website to GitHub Pages, but I made it a separate workflow as I'm envisaging adding specializations here. Like if there is any linting or simple tests we want to execute against the built site HTML we could do them in this workflow without riddling the prod deploy workflow with conditionals.
> Add CI to check that we can build the production site

- _data/release/0_10_0.yaml
- _data/release/0_11_0.yaml
- _data/release/0_1_0.yaml
- _data/release/0_2_0.yaml
- _data/release/0_3_0.yaml
- _data/release/0_4_0.yaml
- _data/release/0_4_1.yaml
- _data/release/0_5_0.yaml
- _data/release/0_5_1.yaml
- _data/release/0_6_0.yaml
- _data/release/0_7_0.yaml
- _data/release/0_8_0.yaml
- _data/release/0_9_0.yaml
Older releases than 0.12.0 have broken links to their asset files. Eg
https://kroxylicious.io/download/0.11.0/
https://github.com/kroxylicious/kroxylicious/releases/tag/v0.11.0kroxylicious-app-0.11.0-bin.zip
> Fix download links in older releases

- .dockerignore
- .github/workflows/jekyll-gh-pages.yml
- .github/workflows/pr-build.yml
- README.md
- _config.yml
- build.sh
Add a build script so that we can build the same way locally and in CI
I'm experimenting with some automation for checking that all the links within the generated HTML are valid, having a way to produce the production build output locally is helpful.
> Add build script

- .github/workflows/pr-build.yml
The intent is to prevent documentation PRs from merging until we manually update the PR with the SHAs.
See matching PR https://github.com/kroxylicious/kroxylicious/pull/2529
The image shas are only available after the image build, which happens in response to the release tag being pushed up. So they are not available at the point we are currently creating the documentation PR.
> Fail PR build if any image SHA placeholders are found

- _sass/kroxylicious.scss
codeblocks imported from the runtime repository are cramped up, lets give them some padding
> Add bottom padding to code blocks in the kroxylicious documentation

- _posts/2025-08-08-release-0_14_0.md
> Release blog 0.14.0

- documentation/0.14.0/html/proxy-quick-start/content.html
yarg, the proxy starts on 9192 by default:
```
2025-08-08 16:25:20 <main> INFO  io.kroxylicious.proxy.model.VirtualClusterModel - Gateway: mygateway, Downstream localhost:9192 => Upstream localhost:9092
```
```
...snip ...
- name: mygateway
portIdentifiesNode:
bootstrapAddress: localhost:9192
```
> Fix quickstart ports

- _layouts/guide.html
- _sass/kroxylicious.scss
Aligns it more with the standalone asciidoc style, which has much nicer margins/padding and a single pixel top border for main sections, more padding on the codeblocks.
Adds a class to the top div surrounding the content so we can specifically target CSS to the guide content.
> Improve guide style
